name: New Issue

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: New Issue
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'new-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'New Issue: ${{ github.event.issue.title }}'
          issue_body: 'New Issue Body: ${{ github.event.issue.body }}'
          labels: 'bug, help wanted: ${{ github.event.issue.title }}'
          assignees: 'actions-cool: ${{ github.event.issue.title }}'