name: New Issue

on: issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: New Issue
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'new-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          runs: 'new-issue ${{ github.event.issue}}'